<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-6K33ESR" failures="0" tests="3" name="com.nfts.Page_Test.Learn_BlogPage_Test" time="2.048" errors="1" timestamp="2023-04-11T20:22:45 IST" skipped="2">
  <testcase classname="com.nfts.Page_Test.Learn_BlogPage_Test" name="setUp" time="2.048">
    <error message="org.openqa.selenium.chrome.ChromeDriver: method &#039;void &lt;init&gt;(org.openqa.selenium.Capabilities)&#039; not found" type="java.lang.NoSuchMethodError">
      <![CDATA[java.lang.NoSuchMethodError: org.openqa.selenium.chrome.ChromeDriver: method 'void <init>(org.openqa.selenium.Capabilities)' not found
at com.nft.qa.base.TestBase.initialization(TestBase.java:72)
at com.nfts.Page_Test.Learn_BlogPage_Test.setUp(Learn_BlogPage_Test.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:176)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setUp -->
  <system-out/>
  <testcase classname="com.nfts.Page_Test.Learn_BlogPage_Test" name="NavigateToLearn_BlogPage" time="0.000">
    <skipped/>
  </testcase> <!-- NavigateToLearn_BlogPage -->
  <system-out/>
  <testcase classname="com.nfts.Page_Test.Learn_BlogPage_Test" name="ValidateLearn_blogPage" time="0.000">
    <skipped/>
  </testcase> <!-- ValidateLearn_blogPage -->
  <system-out/>
</testsuite> <!-- com.nfts.Page_Test.Learn_BlogPage_Test -->
